name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, bcmath, curl, json, pdo, tokenizer

      - name: Install Composer
        run: composer self-update

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Cache Config
        run: php artisan config:cache

      - name: Cache Routes
        run: php artisan route:cache
